#!/bin/bash

[ "$UID" -eq 0 ] || { echo "Execcute como root."; exit 1;}

read -p "Entre com o nome da Unidade: " UNIDADE
read -p "Entre com o nome da Imagem: " IMAGEM

sudo umount /dev/$UNIDADE
sudo partclone.extfs -C -r -d -s $IMAGEM -o /dev/$UNIDADE
